[package]
name = "day12"
version = "0.1.0"
authors = ["eyoson <eyoson@waifu.club>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
